name: Publish Nextcloud Docker image
on:
  schedule:
  - cron: "0 0 * * 1"
  push:
  
jobs:
  push_to_registry:
    name: Build and push nextcloud docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:


      - name: Check out my own repo
        uses: actions/checkout@v2

      - name: Check out offical nextcloud repo
        uses: actions/checkout@v2
        with:
          repository: 'nextcloud/docker'
          path: docker
      
      - run:
          sh ./update-dockerfile.sh
      
      - name: Build office nextcloud image
        uses: docker/build-push-action@v2
        with:
          context: docker/21.0/fpm-alpine
          tags: pestotoast/nextcloud-temp
          push: false
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push my own image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/pestotoast/nextcloud:latest
          push: true
